---

- name: gather compute short hostnames
  set_fact:
    compute_hosts: >-
      {{ groups.compute
      | map('extract', hostvars, ['inventory_hostname_short'])
      | list }}

# vim:ts=2:sw=2:et:syn=yaml:
