---

- hosts: [bastion]
  roles:
    - role: bastion/openssh/configure
      delegate_to: localhost
      become: false

- hosts: [all]
  pre_tasks:
    - set_fact:
        dockerce_version_apt: >-
          {{ dockerce_version_apt | d('5:18.09.9~3-0~ubuntu-bionic') }}
        containerdio_version_apt: >-
          {{ containerdio_version_apt | d('1.2.10-3') }}
        etcd_version: >-
          {{ etcd_version | d('3.4.3') }}
        kubernetes_version: >-
          {{ kubernetes_version | d('1.17.4') }}
        kubernetes_cni_version: >-
          {{ kubernetes_cni_version | d('0.7.5') }}
        helm_version: >-
          {{ helm_version | d('3.1.2') }}

- hosts: [etcd, master, compute]
  roles:
    - role: python3/package/install

- hosts: [etcd, master, compute]
  gather_facts: true
  gather_subset: [network]
  roles:
    - role: network/gather

- hosts: [master, compute]
  roles:
    - role: haproxy/service/install
    - role: haproxy/service/configure
    - role: dockerce/service/install

- hosts: [etcd]
  roles:
    - role: etcd/openssl/bootstrap
      when: inventory_hostname == (groups.etcd | first)
      run_once: true
    - role: etcd/openssl/replicate
    - role: etcd/service/install
    - role: etcd/service/configure

- hosts: [master]
  roles:
    - role: master/kubeadm/install
    - role: master/kubeadm/configure
    - role: master/kubeadm/bootstrap
      when: inventory_hostname == (groups.master | first)
      run_once: true
    - role: master/kubeadm/replicate

- hosts: [compute]
  roles:
    - role: compute/kubeadm/install
    - role: compute/kubeadm/replicate
    - role: compute/kubeadm/configure

- hosts: [master]
  roles:
    - role: master/helm/install

# vim:ts=2:sw=2:et:syn=yaml:
