---
- hosts: bastion
  roles:
    - role: bastion/openssh/configure
      delegate_to: localhost
      become: false
      tags: [bastion]

- hosts: all
  pre_tasks:
    - set_fact:
        dockerce_version_apt: >-
          {{ dockerce_version_apt | d('5:19.03.13~3-0~ubuntu-bionic') }}
        containerdio_version_apt: >-
          {{ containerdio_version_apt | d('1.3.7-1') }}
        etcd_version: >-
          {{ etcd_version | d('3.4.3') }}
        kubernetes_version: >-
          {{ kubernetes_version | d('1.18.6') }}
        kubernetes_cni_version: >-
          {{ kubernetes_cni_version | d('0.8.7') }}
        helm_version: >-
          {{ helm_version | d('3.3.4') }}

- hosts: etcd:master:compute
  roles:
    - role: python3/package/install

- hosts: etcd:master:compute
  gather_facts: true
  gather_subset: [network]
  roles:
    - role: network/gather

- hosts: master:compute
  roles:
    - role: haproxy/service/install
    - role: haproxy/service/configure
    - role: dockerce/service/install

- hosts: etcd
  roles:
    - role: etcd/openssl/bootstrap
      when: inventory_hostname == groups.etcd[0]
      run_once: true
    - role: etcd/openssl/replicate
    - role: etcd/service/install
    - role: etcd/service/configure

- hosts: master
  roles:
    - role: master/kubeadm/install
    - role: master/kubeadm/configure
    - role: master/kubeadm/bootstrap
      when: inventory_hostname == groups.master[0]
      run_once: true
    - role: master/kubeadm/replicate

- hosts: compute
  roles:
    - role: compute/kubeadm/install
    - role: compute/kubeadm/replicate
    - role: compute/kubeadm/configure

- hosts: master
  roles:
    - role: master/helm/install

- hosts: master[0]
  roles:
    - role: master/kubeconfig/fetch
      tags: [kubeconfig]
