---
- name: install binaries (unarchive)
  ansible.builtin.unarchive:
    creates: "{{ item.creates | d(omit) }}"
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    extra_opts: "{{ item.extra_opts | d(omit) }}"
    owner: 0
    group: 0
    mode: "{{ item.mode | d(omit) }}"
  loop:
    - creates: /usr/local/bin/etcd
      src: "https://storage.googleapis.com/etcd/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
      dest: /usr/local/bin/
      extra_opts:
        - --strip-components=1
        - "etcd-v{{ etcd_version }}-linux-amd64/etcd"
        - "etcd-v{{ etcd_version }}-linux-amd64/etcdctl"
      mode: u=rwx,go=rx
  notify:
    - restart etcd

- name: render etcd systemd unit
  ansible.builtin.template:
    dest: /etc/systemd/system/etcd.service
    src: etc/systemd/system/etcd.service.j2
    owner: 0
    group: 0
    mode: u=rw,go=r
  notify:
    - restart etcd

- name: systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
