---
- name: download etcd binary package
  get_url:
    dest: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    url: "https://storage.googleapis.com/etcd/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"

- name: extract etcd binary package
  unarchive:
    dest: /usr/local/bin/
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
      - "etcd-v{{ etcd_version }}-linux-amd64/etcd"
      - "etcd-v{{ etcd_version }}-linux-amd64/etcdctl"
  notify:
    - restart etcd

- name: render etcd systemd unit
  template:
    dest: /etc/systemd/system/etcd.service
    src: etc/systemd/system/etcd.service.j2
  notify:
    - restart etcd

- name: systemd daemon reload
  systemd:
    daemon_reload: true
