---

- name: gather etcd short hostnames
  set_fact:
    etcd_hosts: >-
      {{ groups.etcd
      | map('extract', hostvars, ['inventory_hostname_short'])
      | list }}

# vim:ts=2:sw=2:et:syn=yaml:
