---

- name: gather master short hostnames
  set_fact:
    master_hosts: >-
      {{ groups.master
      | map('extract', hostvars, ['inventory_hostname_short'])
      | list }}

# vim:ts=2:sw=2:et:syn=yaml:
