---
- name: recreate local cache directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/etc/kubernetes/"
    state: "{{ item }}"
    mode: u=rwx,go=r
  delegate_to: localhost
  become: false
  loop:
    - absent
    - directory
  changed_when: false
  run_once: true

- name: pull kubernetes pki to local cache
  ansible.posix.synchronize:
    mode: pull
    src: /etc/kubernetes/
    dest: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/etc/kubernetes/"
    owner: false
    group: false
    checksum: true
    use_ssh_args: true
    rsync_opts: &rsync_opts
      - --include=super-admin.conf
      - --include=HASH
      - --include=TOKEN
      - --include=kube-flannel.yml
      - --include=kube-flannel.yml.DONE
      - --include=kube-vip-cloud-controller.yaml
      - --include=kube-vip-cloud-controller.yaml.DONE
      - --include=pki/
      - --include=pki/ca.crt
      - --include=pki/ca.key
      - --include=pki/sa.key
      - --include=pki/sa.pub
      - --include=pki/front-proxy-ca.crt
      - --include=pki/front-proxy-ca.key
      - --exclude=*
  when: inventory_hostname == groups.master[0]
  changed_when: false
  run_once: true

- name: push kubernetes pki from local cache
  ansible.posix.synchronize:
    mode: push
    src: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/etc/kubernetes/"
    dest: /etc/kubernetes/
    owner: false
    group: false
    checksum: true
    times: false
    use_ssh_args: true
    rsync_opts: *rsync_opts

- name: enable kubelet service
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true

- name: extend kuberentes control plane
  ansible.builtin.shell:
    creates: "{{ item.creates }}"
    cmd: |
      set -eu -o pipefail
      {{ item.cmd }}
    executable: /bin/bash
  loop:
    - creates: /etc/kubernetes/kubelet.conf
      cmd: |
        kubeadm join \
          --node-name={{ ansible_fqdn }} \
          --token=$(head -n1 /etc/kubernetes/TOKEN) \
          --discovery-token-ca-cert-hash=sha256:$(head -n1 /etc/kubernetes/HASH) \
          --control-plane \
          {{ kubevip_address }}:6443
  when: inventory_hostname != groups.master[0]
