---
- name: ensure local cache directory
  file:
    path: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/etc/kubernetes/"
    state: "{{ item }}"
    mode: u=rwx,go=
  changed_when: false
  delegate_to: localhost
  become: false
  run_once: true
  loop:
    - absent
    - directory

- name: pull kubernetes pki to local cache
  synchronize:
    mode: pull
    src: /etc/kubernetes/
    dest: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/etc/kubernetes/"
    checksum: true
    use_ssh_args: true
    rsync_opts: &rsync_opts
      - --include=HASH
      - --include=TOKEN
      - --include=kube-flannel.yml
      - --include=pki/
      - --include=pki/ca.crt
      - --include=pki/ca.key
      - --include=pki/sa.key
      - --include=pki/sa.pub
      - --include=pki/front-proxy-ca.crt
      - --include=pki/front-proxy-ca.key
      - --exclude=*
  when: inventory_hostname == groups.master[0]
  changed_when: false
  run_once: true

- name: push kubernetes pki from local cache
  synchronize:
    mode: push
    src: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/etc/kubernetes/"
    dest: /etc/kubernetes/
    checksum: true
    times: false
    use_ssh_args: true
    rsync_opts: *rsync_opts

- name: extend kuberentes control plane
  shell: |
    kubeadm join \
      --node-name={{ ansible_fqdn }} \
      --token=$(head -n1 /etc/kubernetes/TOKEN) \
      --discovery-token-ca-cert-hash=sha256:$(head -n1 /etc/kubernetes/HASH) \
      --control-plane \
      local-lb:7878
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: inventory_hostname != groups.master[0]
