---
- name: import docker-ce repository gpg key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add docker-ce repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    mode: u=rw,go=

- name: install docker-ce
  apt:
    name:
      - "docker-ce={{ dockerce_version_apt }}"
      - "docker-ce-cli={{ dockerce_version_apt }}"
      - "containerd.io={{ containerdio_version_apt }}"
    state: present
  register: result
  until: result is success
  retries: 20
  delay: 12
