---

- name: import docker-ce repository gpg key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add docker-ce repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- set_fact:
    dockerce_version_apt: >-
      {{ dockerce_version_apt | d('5:18.09.9~3-0~ubuntu-bionic') }}
    containerdio_version_apt: >-
      {{ containerdio_version_apt | d('1.2.10-3') }}

- name: install docker-ce
  apt:
    name:
      - "docker-ce={{ dockerce_version_apt }}"
      - "docker-ce-cli={{ dockerce_version_apt }}"
      - "containerd.io={{ containerdio_version_apt }}"
    state: present
  register: result
  until: result is success
  retries: 20
  delay: 12

# vim:ts=2:sw=2:et:syn=yaml:
