---

- block:

  - lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      regexp: "KUBELET_KUBECONFIG_ARGS=.*--cloud-provider=[^ ]+ "
      state: absent
    register: cloud_provider_result
    changed_when: false
    check_mode: true

  - name: enable cloud provider
    replace:
      dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      regexp: "KUBELET_KUBECONFIG_ARGS="
      replace: "KUBELET_KUBECONFIG_ARGS=--cloud-provider={{ cloud_provider }} "
    when: not cloud_provider_result.changed

  when: cloud_provider | d()

- block:

  - lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      regexp: "KUBELET_KUBECONFIG_ARGS=.*--node-labels=[^ ]+ "
      state: absent
    register: node_labels_result
    changed_when: false
    check_mode: true

  - name: enable node labels
    replace:
      dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      regexp: "KUBELET_KUBECONFIG_ARGS="
      replace: "KUBELET_KUBECONFIG_ARGS=--node-labels={{ node_labels }} "
    when: not node_labels_result.changed

  when: node_labels | d()

- name: initialize compute nodes
  shell: |
    kubeadm join \
      --node-name={{ ansible_fqdn }} \
      --token=$(head -n1 /etc/kubernetes/TOKEN) \
      --discovery-token-ca-cert-hash=sha256:$(head -n1 /etc/kubernetes/HASH) \
      local-lb:7878
  args:
    creates: /etc/kubernetes/kubelet.conf

# vim:ts=2:sw=2:et:syn=yaml:
