---
- name: install binaries (unarchive)
  ansible.builtin.unarchive:
    creates: "{{ item.creates | d(omit) }}"
    remote_src: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    extra_opts: "{{ item.extra_opts | d(omit) }}"
    owner: 0
    group: 0
    mode: "{{ item.mode | d(omit) }}"
  loop:
    - creates: /usr/local/bin/helm
      src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
      dest: /usr/local/bin/
      extra_opts:
        - --strip-components=1
        - linux-amd64/helm
      mode: u=rwx,go=rx

- name: ensure stable repo is present
  ansible.builtin.shell:
    cmd: |
      helm repo add stable \
        https://charts.helm.sh/stable/
  changed_when: false
