---

- name: download helm binary package
  get_url:
    url: "https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: &helm_tgz "/tmp/helm-v{{ helm_version }}-linux-amd64.tar.gz"

- name: deploy helm
  unarchive:
    remote_src: true
    src: *helm_tgz
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
      - linux-amd64/helm
    creates: /usr/local/bin/helm

- name: ensure /usr/local/bin/helm is executable
  file:
    path: /usr/local/bin/helm
    mode: u=rwx,go=rx

# vim:ts=2:sw=2:et:syn=yaml:
