---

- name: boostrap python3 intepreter
  script: "{{ playbook_dir }}/roles/python3/package/install/templates/python3.sh"
  args:
    executable: /bin/bash
    creates: /usr/bin/python3
  register: result
  until: result.rc | d(0) == 0
  retries: 20
  delay: 12

- name: ensure pip packages
  pip:
    name:
      - pyyaml
      - openshift

# vim:ts=2:sw=2:et:syn=yaml:
