---
- name: boostrap python3 intepreter
  ansible.builtin.script:
    cmd: "{{ playbook_dir }}/roles/python3/package/install/templates/python3.sh"
    executable: /bin/bash
    creates: /usr/bin/python3
  register: result
  until: result is success
  retries: 20
  delay: 12
