---
- assert:
    that: bastion_inventory_hostname not in forbidden_inventory_hostnames
    fail_msg: "bastion must not be a part of the cluster"
  vars:
    bastion_inventory_hostname: >-
      {{ groups.bastion | first }}
    forbidden_inventory_hostnames: >-
      {{ (groups.etcd + groups.master + groups.compute) | unique }}

- name: create local .ssh directory tree
  file:
    path: "{{ item }}/"
    state: directory
    mode: u+rwx,g=rx,o=
  loop:
   - "{{ playbook_dir }}/.ssh"
   - "{{ playbook_dir }}/.ssh/config.d"

- name: link extras/.ssh/ to .ssh/
  file:
    src: ../.ssh/
    dest: "{{ playbook_dir }}/extras/.ssh"
    state: link

- name: generate bastion ssh main config
  template:
    dest: "{{ playbook_dir }}/.ssh/config"
    src: sshconfig.j2
    mode: u=rw,g=r,o=

- name: generate bastion ssh cluster config
  template:
    dest: "{{ playbook_dir }}/.ssh/config.d/{{ cluster_name }}"
    src: config.d/sshconfig.j2
    mode: u=rw,g=r,o=
