---
- name: slurp kubeconfig
  ansible.builtin.slurp:
    path: /etc/kubernetes/admin.conf
  register: slurp

- name: update kubeconfig
  ansible.builtin.set_fact:
    kubeconfig: >-
      {{ _document | combine(_update2, recursive=true) }}
  vars:
    _document: >-
      {{ slurp.content | b64decode | from_yaml }}
    _clusters: >-
      {{ [_document.clusters[0] | combine(_update1, recursive=true)] + _document.clusters[1:] }}
    _update1:
      cluster:
        server: "https://{{ kubevip_address }}:6443"
    _update2:
      clusters: "{{ _clusters }}"

- name: store kubeconfig locally
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/.tmp/{{ cluster_name }}/kubeconfig"
    mode: u=rw,go=
    content: "{{ kubeconfig | to_nice_yaml(indent=2) }}"
  delegate_to: localhost
  become: false
  run_once: true
