---

- hosts: master[0]
  tasks:
    - name: EXTRAS | add bitnami repo
      shell: |
        helm repo add bitnami \
          https://charts.bitnami.com/bitnami

    - name: EXTRAS | deploy metrics-server
      shell: |
        helm upgrade --install \
          --namespace kube-system \
          metrics \
          bitnami/metrics-server \
          --set apiService.create=true \
          --set extraArgs.kubelet-insecure-tls=true \
          --set extraArgs.kubelet-preferred-address-types=InternalIP
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

# vim:ts=2:sw=2:et:syn=yaml:
